## 본 코드는 R에 대한 연습을 하기 위한 정리 노트입니다. (version 1.0) 
### 2018.06.13. 홍승재

#### 기본적인 명령어 및 예시에 대한 정리를 하였습니다.

### 목차
1. Data Type
    + 개념 설명
    + 예시 코드


2. 제어문, 연산, 함수
    + 개념 설명 및 예시 코드


3. 벡터 연산


4. 데이터 조작 


3. iris dataset

#### 참고: [R을 이용한 데이터 처리 실무, 서민구](http://r4pda.co.kr/pdf/r4pda_2014_03_02.pdf)

In [23]:
# Setting Global Options
options(warns=-1)
Sys.setlocale(locale="Korean") 
options(encoding="UTF-8") 

[1] "LC_COLLATE=Korean_Korea.949;LC_CTYPE=Korean_Korea.949;LC_MONETARY=Korean_Korea.949;LC_NUMERIC=C;LC_TIME=Korean_Korea.949"

### 1. data type에 대한 설명

1. naming Variable
    + 변수명은 알파벳, 숫자, '_', '.' 등을 사용한다. 
    + <-, <<-, = , ->, ->> 등으로 변수를 assign할 수 있다. (REFERENCE 1 참고)


2. Scala
     + 숫자, NA, NULL, 문자열, 진리값, factor(요인) 등이 포함된다.
     + NULL은 할당되지 않은 객체(?)로써 is.na(null)의 경우 logical(0)을 반환하게 된다. 
     + 진리값의 경우 &, &&, |, ||, ! 의 연산자를 사용 할 수 있다. 
         + &의 경우는 벡터의 요소 "끼리" 연산을 할 때 활용되며, &&의 경우는 벡터 그 자체 간의 연산을 할 때 활용된다.
     + Factor의 경우 범주형(categorical) 변수를 위한 타입으로써 사전에 지정된 요인 값만 들어 갈 수 있다. - 자세한 건 아래 참고


3. vector
    + c()를 통해 나열을 한다. 
    + c()내에 나열되는 값들은 동일한 유형의 스칼라여야 한다. (type에도 우선순위로 적용되는 게 있다)
    + 벡터는 중첩될 수 없다. c(1,2,3,c(1,2,3)) = 1, 2, 3, 1, 2, 3 으로 반환한다.
    + 벡터 내 데이터에 접근하기 위해서는 X[n]으로 입력을 한다.
    + 벡터 연산 시 벡터는 집합으로 인식하여 연산을 하게 된다. 
    
    
4. matrix
    + m[1,]은 → 의 방향 / 행 / SNA에서 outdegree (sender)
        + 즉, 2행은 두 번째 줄에 있는 vector들을 의미
    + m[,1]은 ↓ 의 방향 / 렬 / SNA에서 indegree (receiver)
        + 즉, 2열은 두 번째 column에 있는 vector들을 의미
    + 즉 행렬이름[행인덱스, 열인덱스]로 접근을 하게 된다. 
        + 인덱스에는 벡터를 넣을 수 있다. X[c(1,3),c(2:4)] 이런 식으로 말이다. 
        + dimnames를 통하여 행과 열에 이름을 부여했다면 이름을 직접 사용하여 matrix를 추출 할 수 있다. 
    + 행렬을 연산하기 위해서는 일반 프로그래밍처럼 * 혹은 / 을 사용한다. 덧셈은 + 이고 뺄셈은 - 이다. (기타 연산은 아래에 예시로 설명)


5. Array - Matrix의 확장
    + Array는 n차원의 행렬이다. 배열의 차원은 dim()함수를 통해 알 수 있다. 


6. data.frame
    + 가장 중요한 자료형
    + data.frame의 경우 하나의 컬럼만 선택을 할 경우, 벡터로 결과가 처리되기 때문에 하나의 column만 선택하기 위해서는 drop=FALSE 옵션을 지정해야 한다. 


7. list
    + list(키=값, 키=값, ... ) 등으로 정의된다. 또한 각 값이 모두 스칼라일 필요도 없으며, 타입이 달라도 저장이 가능하다.
    + 리스트 내 데이터 접근을 위해서는 X[[n]]으로 입력한다. 즉, [[n]]으로 입력을 할 경우, X내 키1의 n번째 값 ... 키m의 n번째 값까지 반환을 한다.
    + X[n]의 경우는 키n의 서브 리스트를 반환하는 것이다. 

### About Commands

In [49]:
# 진리값
print(TRUE & TRUE)
print(TRUE & FALSE)
print(TRUE|TRUE)
print(TRUE|FALSE)
print(!TRUE)
print(c(TRUE,TRUE) & c(TRUE,FALSE)) # column 내 원소 간 비교
print(c(TRUE,TRUE) && c(TRUE,FALSE)) # column 자체 비교

# factor
gender <- factor("m", c("m","f")) # 현재 gender 변수에는 m이라는 factor가 들어가 있지만, factor의 전체 범위는 {m, f}임을 암시한다.
print(gender)

print(nlevels(gender)) # nlevel을 통하여 범주의 수를 확인한다.
print(levels(gender)) # levels을 통하여 범주의 목록을 확인한다.

print(levels(gender)[2]) # 범주의 목록 중 두번째를 출력한다.

levels(gender) <- c('male','female') # gender의 level의 값을 변경한다. 
print(gender)

# 기본적으로 factor에는 order가 없기 때문에 ordering을 하기 위해서는 
print(ordered(c("a","b","c"))) 

print(factor(c("a","b","c"), ordered=TRUE)) # 이렇게 두 가지 방식이 존재한다. (< 으로 ordered가 표시된다.)

[1] TRUE
[1] FALSE
[1] TRUE
[1] TRUE
[1] FALSE
[1]  TRUE FALSE
[1] TRUE
[1] m
Levels: m f
[1] 2
[1] "m" "f"
[1] "f"
[1] male
Levels: male female
[1] a b c
Levels: a < b < c
[1] a b c
Levels: a < b < c


In [64]:
# Vector
print(seq_along(c('a','b','x'))) # 주어진 데이터의 길이만큼 1 ~ N으로 구성된 벡터를 반환한다. 
print(seq_len(5)) # N값이 주어지면 1 ~ N으로 주어진 벡터를 반환한다.

x <- c(1,2,3)
names(x) <- c("x","y","z") # 벡터에도 이름을 넣을 수 있다. 
print(x)

# 벡터내 데이터 접근은 []으로 표시한다.
print(x[2])
print(x[-1])
print(x[c(1,3)])
print(x[1:3])
print(x["z"]) # 벡터에 정의된 이름으로도 반환 할 수 있다.

# 벡터의 길이는 length() 혹은 NROW()로 알 수 있다. 
print(length(x))
print(NROW(x))
print(nrow(x)) # matrix가 아니기 때문에 NULL을 반환한다.

# 벡터 연산 (%in% 을 통하여 해당 값이 벡터에 포함되어 있는지 확인한다)
print("a" %in% c("a","b","c"))
print(setdiff(c("a","b","c"),c("a","d"))) # 차집합 (A-B)
print(union(c("a","b","c"),c("a","d"))) # 합집합 (A+B)
print(intersect(c("a","b","c"),c("a","d"))) # 교집합
print(setequal(c("a","b","c"),c("a","d"))) # 집합 간 비교

# sequential numbering
print(seq(1,5))
print(1:5)
print(seq(1,5,2)) # 3번째는 증가치

# repetition numbering
print(rep(1:2, 5)) # 5번의 loop로써 반복
print(rep(1:2, each=5)) # 각각 5번

[1] 1 2 3
[1] 1 2 3 4 5
x y z 
1 2 3 
y 
2 
y z 
2 3 
x z 
1 3 
x y z 
1 2 3 
z 
3 
[1] 3
[1] 3
NULL
[1] TRUE
[1] "b" "c"
[1] "a" "b" "c" "d"
[1] "a"
[1] FALSE
[1] 1 2 3 4 5
[1] 1 2 3 4 5
[1] 1 3 5
 [1] 1 2 1 2 1 2 1 2 1 2
 [1] 1 1 1 1 1 2 2 2 2 2


In [75]:
# 리스트
x <- list(name ="hong", age=30, gender="male") # null list를 만들 수도 있다. x <- list()
print(x)

# list는 스칼라, 벡터 간의 차이를 두지 않는다. 
x <- list(name ="hong", age=c(29,30,31), gender="male")
print(x)

# 따라서 list 내에 list를 중첩시켜 만들 수 있다.
x <- list(a=list(name="hong", age=30), b=list(name="hong2",age=29), c=c(1,2,3))
print(x)

# 리스트 내의 데이터에 접근하기 위해서는 $키 값에 접근해야 하며 이는 [[n]]을 통해 접근한다.
print(x[[2]]) # x$b의 리스트를 반환한다.
print(x[1]) # x의 첫 번째 키 값 자체를 반환해버린다. 

$name
[1] "hong"

$age
[1] 30

$gender
[1] "male"

$name
[1] "hong"

$age
[1] 29 30 31

$gender
[1] "male"

$a
$a$name
[1] "hong"

$a$age
[1] 30


$b
$b$name
[1] "hong2"

$b$age
[1] 29


$c
[1] 1 2 3

$name
[1] "hong2"

$age
[1] 29

$a
$a$name
[1] "hong"

$a$age
[1] 30




In [106]:
# matrix
x <- matrix(c(1:10), nrow=5) # 5행, 2열
print(x)
x <- matrix(c(1:10), ncol=5) # 5열, 2행
print(x)
x <- matrix(c(1:10), nrow=5, byrow=T) #행부터 채워나가는 option
print(x)

# naming row / cols
x <- matrix(c(1:6), nrow=2, dimnames = list(c("a","b"), c("x","y","z")))
print(x)

# 행렬 내 데이터 접근
print(x[2,3])
print(x[1:2,-3])
print(x[2,c(1,3)]) # 인덱스에 vector를 적용 할 수 있다.
print(x["b",c("y","z")]) # 인덱스에 붙여진 이름을 적용 할 수도 있다.

# 행렬 연산
print(x*2)
print(x/2)
print(x + (x^2))
print(x - (x/2))
# %*% 행렬 곱 (정방행렬 혹은 곱의 row/col이 맞아야함), t(): 전치행렬, solve(): 역행렬)

# 행렬의 차원은 ncol, nrow로 구한다.

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8
[5,]    9   10
  x y z
a 1 3 5
b 2 4 6
[1] 6
  x y
a 1 3
b 2 4
x z 
2 6 
y z 
4 6 
  x y  z
a 2 6 10
b 4 8 12
    x   y   z
a 0.5 1.5 2.5
b 1.0 2.0 3.0
  x  y  z
a 2 12 30
b 6 20 42
    x   y   z
a 0.5 1.5 2.5
b 1.0 2.0 3.0


In [109]:
# array
x <- array(1:12, dim=c(2,2,3)) # 2*2*3 행렬 (3겹의 2*2 행렬)
print(x)
print(x[1,1,3]) # 인덱스


, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12

[1] 9


#### data.frame은 정말 중요하다. 다양한 함수도 적용 할 수 있고 데이터 관리할 때 가장 편리하기 때문이다. 

In [123]:
d <- data.frame(x=c(1:5),y=seq(1,10,2),z=c("a","b","c","x","y"))
print(d)
d$v <- c(3:7)
print(d)

# 인덱싱
print(d$x)
print(d[1,])
print(d[2,3])
print(d[c(1,3),-2])
print(d[3,c("x","z")])
print(d[,c("x"),drop=FALSE]) # 하나의 column만 선택 할 경우 data.frame의 모양이 아닌 vector로 반환되기에 drop FALSE option을 한다.

  x y z
1 1 1 a
2 2 3 b
3 3 5 c
4 4 7 x
5 5 9 y
  x y z v
1 1 1 a 3
2 2 3 b 4
3 3 5 c 5
4 4 7 x 6
5 5 9 y 7
[1] 1 2 3 4 5
  x y z v
1 1 1 a 3
[1] b
Levels: a b c x y
  x z v
1 1 a 3
3 3 c 5
  x z
3 3 c
  x
1 1
2 2
3 3
4 4
5 5


In [124]:
str(d) #자료요약
head(d,2) #자료 일부 보이기

d <- data.frame(1:3)
print(d) # as.data.frame이나 혹은 바로 data frame으로 설정할 경우 df의 이름이 없다. 

colnames(d) <- c('val') # 따라서 행의 이름을 새기거나
rownames(d) <- c('x','y','z') # 열의 이름을 새길 수 있다.
print(d)

'data.frame':	5 obs. of  4 variables:
 $ x: int  1 2 3 4 5
 $ y: num  1 3 5 7 9
 $ z: Factor w/ 5 levels "a","b","c","x",..: 1 2 3 4 5
 $ v: int  3 4 5 6 7


x y z v
1 1 1 a 3
2 2 3 b 4

  X1.3
1    1
2    2
3    3
  val
x   1
y   2
z   3


In [130]:
# indexing (%in%) - %%와 관련한 연산자를 따로 정리할 필요가 있다. (2018.06.13.)
df <- data.frame(a=1:3,b=4:6,c=7:9)
print(df[,names(df) %in% c("b","c")]) # 즉 df라는 데이터 프레임 안에서 %in% 의 b, c column이 있는지 확인하고 반환을 하는 것이다.
print(df[,names(df) %in% c("b","d"),drop=FALSE]) #d라는 column이 없기 때문에 반환을 하지 않는다. 
print(df[,!names(df) %in% c("a")]) #a column을 제외하고 찾은 뒤 반환한다. 

  b c
1 4 7
2 5 8
3 6 9
  b
1 4
2 5
3 6
  b c
1 4 7
2 5 8
3 6 9


In [134]:
# CLASS 판별 (=class() / =str() / =is.TYPE() / =as.TYPE())
# numeric, matrix, list, dataframe인지 판별한다. 

x <- c("m","f")
print(as.factor(x)) # 알파벳 순서상 f가 m보다 앞서기 때문에 level 순서가 f m으로 나온다. 
print(as.numeric(as.factor(x))) # 이에 따라서 numeric화 시킬 경우 m=2, f=1 (level에 의해 정의된)으로 반환이 된다.

print(factor(c("m","f"),levels=c("m","f"))) 
# factor 함수를 통해 level option을 걸어야 원하는 순서대로 factor level을 설정 할 수 있다. 

[1] m f
Levels: f m
[1] 2 1
[1] m f
Levels: m f


### 2. 제어문, 연산, 함수
#### 본 내용은 특성 상 개념적인 내용 위주로 정리를 할 계획이다.

1. 제어문
    + IF: if(TRUE) {연산1} else {연산2} 으로 구성된다. 
    + FOR: for(i in 1:10) {연산1} else {연산2}으로 구성된다.
    + WHILE: 역시 유사하며, err가 날 때까지 연산을 한다.
 

2. 결측치(NA)
    + 결측치가 있을 경우, 연산 과정에서 모두 결측치로 반환을 한다.
        + NA & TRUE = NA
        + NA + 1 = NA
        + 머신러닝 패키지인 [caret](https://cran.r-project.org/web/packages/caret/index.html) 을 통하여 na.omit, na,pass, na.fail 등을 na.action의 인자로 받아 NA 처리 과정을 자세하게 할 수 있다.

In [138]:
# how to deal with NA
sum(c(1, 2, 3, NA))
sum(c(1, 2, 3, NA), na.rm =T) # 따라서 na.rm 이라는 조건을 통하여 NA를 무시하고 진행 할 수 있다.

[1] NA

[1] 6

3. 함수의 정의
    + 함수명 <- function(인자1, 인자2, ...) {함수 구문} 으로 정의된다.
    + 일반적으로 함수 구문 내에서 return()을 적용하는게 명확하다.
    + 함수1에서 정의된 인자를 함수2의 정의 과정에서 활용 할 수 있다.
        + f <- function(x,y){~} / g <- function(z, ...){~ f(...)}을 통하여 f에서 정의된 인자 x, y를 z에서 ...으로 모두 끌여들어 새로운 함수 내의 구문으로 만들 수 있다.
    + 함수 안에 함수를 정의 할 수 있다.
        + f <- function(x, y) { g <- function(y){~}} 을 적을 경우, y의 인자는 g 함수와 f 함수에서 사용되게 된다.
    

4. 스코프(scope)
    + 코드에 기술한 변수가 어디에서 사용이 가능한지와 관련한 범위로써 lexical scope를 사용한다. 
    + 즉, 콘솔 상에서 선언된 변수는 모든 곳에서 사용이 가능하다 
    + 그러나 함수 내부에서 변수 이름이 주어질 경우 그 변수를 찾는 범위는 함수 내부가 우선이 된다 (local in STATA)
    + 전역 -> 함수 -> 함수 내부 함수 -> .. 으로 스코프의 우선 순위가 결정된다.
        + f <- function(x,y){a <- 2, g<- function(y){a+1}} 일 경우 g 함수 내부에서 a가 없기 때문에 f 함수에서 선언된 a를 먼저 참고하며, 그마저도 f에 없을 경우 전역에 존재하는 a를 불러온다.

In [141]:
# scope와 관련한 예제 코드

# 예시1
b <- 0 # 전역으로 b가 0이 선언된다. 

f <- function () {
    a <- 1 # f 함수 내에서 a에 1이 선언된다. 
        g <- function () {
            a <- 2  # 1이 선언된 a에 2가 선언된다. 그러나 이 선언은 g함수 내에서만 유효하다. 
            b <- 2  # 동일하다.
            print (a)
            print (b)
        }
    g() # g 함수 자체에 적용된 내용은 없다. 
    print (a) # f함수 내에서 적용된 a를 반환한다.
    print (b) # 최초에는 f함수에 적용된 b를 적용해야 하지만, b에는 아무 값이 없기 때문에 전역에서 선언된 b가 print된다.  
}

f()

#예시2
b <- 0

f <- function () {
    a <- 1
        g <- function () {
            a <<- 2 # <<- 를 사용하게 될 경우, g 함수 뿐만 아니라, f와 전역 모두에 적용되는 최우선적인 선언이 된다. 
            b <<- 2
            print (a)
            print (b)
        }
    g()
    print (a)
    print (b)
}

f()

[1] 2
[1] 2
[1] 1
[1] 0
[1] 2
[1] 2
[1] 2
[1] 2


### 3. 벡터 연산
#### 서민구, 2014의 p.71 ~ 74를 발췌했드며, p. 75 ~ 80 까지의 '객체 불변성', '모듈', '큐 패턴'은 추후에 읽어보도록 한다. 

"벡터 연산이 중요한 이유는 for문등을 사용해 값을 하나씩 처리해나가는대신 벡터나 리스트를 한번에 처리하는 것이 더 효율적이고 편리하기 때문이다... 벡터끼리 연산하는 것도 가능하다. 앞서 진리값 (페이지 38)에서 설명하였듯이 벡터간 연산시에는 &&가 아니라 &를 사용한다."(서민구, 2014: 71-72)

"R에서는 모든 것이 객체이다. 또 객체는 함수 호출시 일반적을 값으로 전달된다. 이를 변수에 대한 참조(Reference)에 의한 방식에 대비해 값에 의한 전달(Pass By Value)이라고 한다. 값으로 전달된다는 말은 객체가 복사되어 함수로 전달된다는 의미이다. 예를들어 다음과 같이 데이터 프레임을 함수에 주었을 때 함수 내부에서 수행한 변경은 원래 객체에는 반영되지 않는다. 왜냐하면 함수 f안에서의 df2란 f를 호출한 측에서 넘긴 df 객체를 가리키는 참조가 아니라 넘겨받은 df를 복사한 새로운 df2이기 때문이다. [[Reference]](http://homepage.stat.uiowa.edu/~luke/R/references.html) (서민구, 2014: 73-74).

"여기까지 읽은 독자는 ‘그렇다면 객체가 함수에 넘겨질때마다 새로운 객체를 만들어야하므로 메모리 사용량이 너무 많아지지 않을까?’라는 의심을 품게 될 것이다. 실제로 매번 복사가 일어나야 한다면 그러한 부담이 있는 것이 사실이다. 그러나 R을 포함한 현대적 언어들은 함수 호출시 곧바로 객체를 복사하기 보다는 객체의 값을 바꿀 필요가 있을 때만 복사를 수행하는 Copy On Write 기법을 사용한다. [Copy on Write](https://en.wikipedia.org/wiki/Copy-on-write)에서는 데이터 프레임 등의 객체를 어떤 함수에 넘겼을 때 그 함수가 객체 내부 값을 바꾸는 시점에 이르러서야 값이 수정된 새로운 복사본을 만든다." (서민구, 2014: 74-75).


1. 객체 목록 담기 및 삭제
    + ls(): 메모리 상에 만들어진 전체 객체의 목록을 담아내는 함수이다.
    + rm(): 해당 객체를 삭제하는 함수이다
    + rm(list=ls()): 전체 객체의 목록을 삭제하는 함수이다.

### 4. 데이터 조작
1. 파일 입출력
    + 함수
    
    
2. 데이터 조작 관련 함수 (with iris & mtcars dataset)
    + rbind, cbind
    + apply 계열 함수
    + 기타 함수


3. 데이터 조작 관련 패키지

In [135]:
head(iris)
str(iris)
head(mtcars)
str(mtcars)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species   
1 5.1          3.5         1.4          0.2         setosa    
2 4.9          3.0         1.4          0.2         virginica 
3 4.7          3.2         1.3          0.2         versicolor
4 4.6          3.1         1.5          0.2         setosa    
5 5.0          3.6         1.4          0.2         virginica 
6 5.4          3.9         1.7          0.4         versicolor

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Ord.factor w/ 3 levels "setosa"<"versicolor"<..: 1 3 2 1 3 2 1 3 2 1 ...


mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...


기본적인 데이터인 iris와 mtcars를 바탕으로 연습을 할 예정이다.

In [17]:
# attach(iris) # iris dataset을 검색 경로에 올려놓아 변수명으로 바로 접근 할 수 있다. 
# attach(mtcars)

# factor 연습
is.factor(iris$Species)
nlevels(iris$Species) # 모든 범주의 목록을 반환한다.
iris$Species <- ordered(c("setosa","virginica","versicolor")) # factor를 -> 순서대로 ordering한다. 이후 iris$Species에 넣었다.
is.ordered(iris$Species)
iris$Species # ordering을 할 경우 범주화된 순서대로 데이터가 재배열 되는 듯?

[1] TRUE

[1] 3

[1] TRUE

[1] setosa     virginica  versicolor setosa     virginica  versicolor
  [7] setosa     virginica  versicolor setosa     virginica  versicolor
 [13] setosa     virginica  versicolor setosa     virginica  versicolor
 [19] setosa     virginica  versicolor setosa     virginica  versicolor
 [25] setosa     virginica  versicolor setosa     virginica  versicolor
 [31] setosa     virginica  versicolor setosa     virginica  versicolor
 [37] setosa     virginica  versicolor setosa     virginica  versicolor
 [43] setosa     virginica  versicolor setosa     virginica  versicolor
 [49] setosa     virginica  versicolor setosa     virginica  versicolor
 [55] setosa     virginica  versicolor setosa     virginica  versicolor
 [61] setosa     virginica  versicolor setosa     virginica  versicolor
 [67] setosa     virginica  versicolor setosa     virginica  versicolor
 [73] setosa     virginica  versicolor setosa     virginica  versicolor
 [79] setosa     virginica  versicolor setosa     virginica  versicolor
 [85] setosa     virginica  versicolor setosa     virginica  versicolor
 [91] setosa     virginica  versicolor setosa     virginica  versicolor
 [97] setosa     virginica  versicolor setosa     virginica  versicolor
[103] setosa     virginica  versicolor setosa     virginica  versicolor
[109] setosa     virginica  versicolor setosa     virginica  versicolor
[115] setosa     virginica  versicolor setosa     virginica  versicolor
[121] setosa     virginica  versicolor setosa     virginica  versicolor
[127] setosa     virginica  versicolor setosa     virginica  versicolor
[133] setosa     virginica  versicolor setosa     virginica  versicolor
[139] setosa     virginica  versicolor setosa     virginica  versicolor
[145] setosa     virginica  versicolor setosa     virginica  versicolor
Levels: setosa < versicolor < virginica

In [20]:
head(iris,9) # 그러하다. factor를 순서로 만들어버리면 해당 순서대로 정렬이 된다. 
str(iris) # ordered factor라고 내용이 변경되어 출력된다. 

Sepal.Length Sepal.Width Petal.Length Petal.Width Species   
1 5.1          3.5         1.4          0.2         setosa    
2 4.9          3.0         1.4          0.2         virginica 
3 4.7          3.2         1.3          0.2         versicolor
4 4.6          3.1         1.5          0.2         setosa    
5 5.0          3.6         1.4          0.2         virginica 
6 5.4          3.9         1.7          0.4         versicolor
7 4.6          3.4         1.4          0.3         setosa    
8 5.0          3.4         1.5          0.2         virginica 
9 4.4          2.9         1.4          0.2         versicolor

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Ord.factor w/ 3 levels "setosa"<"versicolor"<..: 1 3 2 1 3 2 1 3 2 1 ...


Reference List
1. [Assign과 관련된 부분](http://stat.ethz.ch/R-manual/R-patched/library/base/html/assignOps.html)
 + ->, ->> 와 = 사이에 발생하는 오류 및 차이점에 대한 간략한 설명이 있다. 